name: SnowballStacker
main: haveric.snowballStacker.SnowballStacker
version: 1.0
dev-url: http://dev.bukkit.org/server-mods/snowballstacker/
description: >
             Snow piles up when thrown
commands:
