name: SnowballStacker
main: haveric.snowballStacker.SnowballStacker
version: 1.0.3
author: haveric
dev-url: http://dev.bukkit.org/server-mods/snowballstacker/
softdepend: [WorldGuard]
description: >
             Snow piles up when thrown and turns water into ice
commands:
    snowballstacker:
        description: Informs the user about the current settings
        usage:
permissions:
    snowballstacker.*:
        description: Gives access to all SnowballStacker Commands
        children:
            snowballstacker.adjust: true
            snowballstacker.stack: true
            snowballstacker.freeze: true
    snowballstacker.stack:
        description: Allows user to stack piles of snow by throwing snowballs.
        default: false
    snowballstacker.freeze:
        description: Allows user to freeze water by throwing snowballs.
        default: false
    snowballstacker.adjust:
        description: Allows user/group to use setfreeze and setsnow commands
        default: false