name: SnowballStacker
main: haveric.snowballStacker.SnowballStacker
version: 1.0.2
author: haveric
dev-url: http://dev.bukkit.org/server-mods/snowballstacker/
softdepend: [WorldGuard]
description: >
             Snow piles up when thrown and turns water into ice
commands:
    snowballstacker:
        description: Informs the user about the current settings
        usage:
